import React from "react";
import { Box, CssBaseline, Container } from "@mui/material";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Providers from "./Providers";
import Navbar from "../components/widgets/Navbar";
import Footer from "../components/widgets/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <CssBaseline />
          {/* Outer layout container */}
          <Box
            sx={{
              display: "flex",
              flexDirection: "column",
              minHeight: "100vh", // Full screen height
              /*background:
                "linear-gradient(188deg, rgba(200, 115, 162, 1) 14%, rgba(215, 169, 79, 1) 30%, rgba(255, 255, 255, 1) 100%)", */
            }}
          >
            {/* Navbar */}
            <Box
              component="header"
              sx={{
                textAlign: "center",
                py: 2,
              }}
            >
              <Navbar />
            </Box>

            {/* Main content */}
            <Box
              component="main"
              sx={{
                flex: 1,
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                py: 3,
              }}
            >
              <Container maxWidth="lg">{children}</Container>
            </Box>

            {/* Footer */}
            <Box
              component="footer"
              sx={{
                py: 3,
              }}
            >
              <Footer />
            </Box>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
